name: Build Container Image

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  build-and-push:
    name: build and push to ghcr
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,format=short
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

  scan-cve:
    name: scan CVE on the image
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v5
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha,prefix=,format=short
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          severity: CRITICAL,HIGH,MEDIUM
          output: trivy-results.sarif
          format: sarif
          hide-progress: true
          ignore-unfixed: true
          exit-code: 0
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy-image-scan

  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - uses: cachix/install-nix-action@v31
      - name: Cargo lambda build
        shell: nix shell nixpkgs#cargo-lambda --quiet --command bash {0}
        run: cargo lambda build --release
      - name: Upload the artifact bootstrap.zip
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap
          path: ./target/lambda/totp-server/bootstrap.zip
          if-no-files-found: error
          retention-days: 5
