name: Checks

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  typos:
    runs-on: ubuntu-latest
    name: check misspelling by typos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#typos --quiet --command bash {0}
        run: typos --hidden --exclude .git --format brief

  cargo-clippy:
    runs-on: ubuntu-latest
    name: lint rust code by clippy
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cargo clippy
        # The `-- -D warnings` flag treats all warnings as errors.
        run: cargo clippy --release -- -D warnings

  cargo-doc:
    runs-on: ubuntu-latest
    name: lint rust docstring by rustdoc
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cargo doc
        run: cargo doc

  trivy-fs:
    name: use trivy to scan files
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: fs
          severity: CRITICAL,HIGH,MEDIUM
          skip-dirs: ./target
          output: trivy-results.sarif
          format: sarif
          hide-progress: true
          ignore-unfixed: true
          exit-code: 1
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy-fs-scan

  trivy-config:
    name: use trivy to scan configs
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: config
          severity: CRITICAL,HIGH,MEDIUM
          output: trivy-results.sarif
          format: sarif
          hide-progress: true
          ignore-unfixed: true
          exit-code: 1
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy-config-scan
