name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "5 3 * * 6" # At 03:05, only on Saturday

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run renovate
        uses: renovatebot/github-action@v43.0.4
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
