name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0/15 * * * *" # Run every 15 minutes

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run renovate
        uses: renovatebot/github-action@v43.0.4
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
