name: Tests and Code Coverage

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    name: tests and code coverage
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - uses: cachix/install-nix-action@v31
      - name: Run tests and gather code coverage data
        shell: nix shell nixpkgs#cargo-tarpaulin --quiet --command bash {0}
        run: cargo tarpaulin --engine llvm --out xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
